import type { Metadata } from "next";

import "./globals.css";

import { Noto_Sans_KR } from "next/font/google";

const notoSansKR = Noto_Sans_KR({
  preload: false,
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "ART MAP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={`${notoSansKR.className} antialiased bg-[#e4e4e4]`}>
        {children}
      </body>
    </html>
  );
}
